# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62e7c0d98210e7b539914b74e4299d171223808e1e7b9db11b868305a025f81b2efaa696d8fe7183e58408d2d705a9a64241003112669f402490de1e8484b52b

test:
  secret_key_base: db192863ab22b08132dc5216a47c338231b6137f05f501d8ebe2b4b82d5008d80c4f5f73025b0a7165ef0ba6e640c9cd2056389c09eef532c61a67d4f0a58090

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
